### ISSUE TITLE
Remove dependency on unittest2

### ISSUE THREAD

**Issue by mcepl** [quandl/quandl-python#113]
Quandl doesn't support Python 2.6 anyway, so there is no reason why to bother with adding an additional dependency on ``unittest2``.

[This patch](https://github.com/quandl/quandl-python/files/2283184/remove_unittest2.patch.txt) fixes the situation.

**Comment by mbasset** [comment]
Hi @mcepl,

This sounds like a good suggestion and your patch seems reasonable at a first glance. Rather than a patch however can you please fork and provide a PR with this patch that we can review and comment with these changes. In anticipation of that we will close this issue as we can discuss further on the PR.

**Comment by mcepl** [comment]
I was filing twenty or so such patches last week. I really don't want to create useless forks for each of them. Do I have to?

**Comment by sebix** [comment]
@mbasset Seriously? Someone writes a patch for you fixing your software and you reject it because the author did not already have enough work with your software?
