### ISSUE TITLE
Support for current more-itertools?

### ISSUE THREAD

**Issue by sebix** [quandl/quandl-python#137]
Is it planned to support the current version of more-itertools?

https://github.com/quandl/quandl-python/blob/d2db903bbaa72a341f0ad7ab1b49e645b84012be/setup.py#L25

We are now dropping this package in opensuse because of this requirement.

**Comment by couture-ql** [comment]
Hi there,

Apologies for a late response.

At the moment we're trying to support a wide audience, thus python 2.7 as well as 3.x.  `more-itertools` has [dropped support](https://pypi.org/project/more-itertools/6.0.0/) for python 2.7 as of 6.0.0.  We're well aware of 2.7's EOL in 2020.

We are currently considering development plans that can appropriately support multiple versions of python.

As this may complicate our release process we are considering a few ideas before we commit to a particular plan.

>We are now dropping this package in opensuse because of this requirement.
Ok.  As I'm not aware of opensuse roadmap, are package maintainers for opensuse only supporting 3.x in preparation for the 2020 EOL of 2.7?

We are considering keeping our v3.x track to support 2.7 until it's EOL. Thus, we can bump more-itertools.  We'll need to be considerate of numpy because 1.17 requires python >=3.5.

**Comment by sebix** [comment]
>  Ok. As I'm not aware of opensuse roadmap, are package maintainers for opensuse only supporting 3.x in preparation for the 2020 EOL of 2.7?

Yes, same for Debian, Fedora etc.

**Comment by alexchandel** [comment]
Python 2.7 has been EOL'd, and is no longer supported.  Please delete your ancient, bug-ridden dependency on more-itertools <=5.0.0.

**Comment by couture-ql** [comment]
Sure thing.  We're going through the motions right now to get rid of this in our master branch.  We have customers that do rely on some ancient tech, and are going to have a maintenance track for these.  Everyone else should be following master.

**Comment by jjmar** [comment]
We've released Quandl `3.5.0` which drops the cap on more-itertools. Please update to that version if you haven't already.
