### ISSUE TITLE
ERROR"No module named 'inflection"

### ISSUE THREAD

**Issue by Kami-in-the-house** [quandl/quandl-python#148]
The error poped up after I imported the quandl!  I installed through pip install quandl. 
Can fix this problem?

Quandl version: 3.4.8
python version: 3.6.3  64-bit
Window version:  Windows 7 pro (64-bit)

![圖片](https://user-images.githubusercontent.com/58814174/70711844-5bd27e00-1d1d-11ea-9634-91d67c8c7351.png)

**Comment by couture-ql** [comment]
Hi Kami,

I suspect that at the time you tried the inflection package was not present on the Anaconda repository --  but that's merely a guess.  It appears there are a few variants running around on Anaconda, but the [conda-forge variant](https://anaconda.org/conda-forge/inflection/labels) appears to match what is available on pypi.

Since this issue out of our control, I'm going to close it.
